# Generated by Django 6.0.1 on 2026-02-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wassaya_rdv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('kind', models.CharField(choices=[('PATIENT_CREATED', 'Patient - RDV created (PENDING)'), ('PATIENT_STATUS', 'Patient - RDV status changed'), ('PATIENT_CANCELLED', 'Patient - RDV cancelled'), ('DOCTOR_NEW_REQUEST', 'Doctor - new RDV request'), ('OTHER', 'Other')], default='OTHER', max_length=40)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=10)),
                ('error_message', models.TextField(blank=True, default='')),
                ('template', models.CharField(blank=True, default='', max_length=200)),
                ('has_ics', models.BooleanField(default=False)),
            ],
        ),
    ]
