# Generated by Django 6.0.1 on 2026-02-06 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wassaya_clinic', '0001_initial'),
        ('wassaya_rdv', '0003_appointment_reminder_1h_sent_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'datetime'], name='wassaya_rdv_status_378d17_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'datetime'), name='uniq_doctor_slot'),
        ),
    ]
